nodejs/week3
Rasim-Deniz/meal-sharing pull request #1
Opened 2021-05-16 01:02 UTC by Rasim-Deniz

2021-05-16 12:54 UTC, florinmaticu requested changes

2021-05-16 12:54 UTC, flom84 commented on src/backend/api/meals.js
> +      const meals = await knex("meal")
i believe the name of the database is `meals` and not `meal` at least according to `database_dump_meals.sql`.

2021-05-16 12:54 UTC, flom84 commented on src/backend/api/meals.js
> +    throw error;
returning an error response is better here than throwing an exception that might crash your server

2021-05-18 15:18 UTC, Rasim-Deniz commented on src/backend/api/meals.js
> +      const meals = await knex("meal")
The database I created is named meal instead of meals. I should change it I guess.

2021-05-19 13:00 UTC, merged

2021-05-19 13:02 UTC, Rasim-Deniz commented on src/backend/api/meals.js
> +    throw error;
Thanks for your time. Changed it.